version: '3.5'
services:

  #Definicion servicio mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=tpsbd
      - MYSQL_USER=tps
      - MYSQL_PASSWORD=gcOiwC4P3vO5ZVft
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    networks:
      - RED_TPS
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql

  #Definicion servicio msusuarios
  msusuarios:
    container_name: msusuarios
    image: figonzal/msusuarios:v1.0.0
    networks:
      - RED_TPS
    depends_on:
      - mysql
      - mscategorias

  #Definicion servicio msfavoritos
  msfavoritos:
    container_name: msfavoritos
    image: figonzal/msfavoritos:v1.0.0
    networks:
      - RED_TPS
    depends_on:
      - mysql
      - mscategorias
      - msusuarios
      - msnoticias
  
  #Definicion servicio mscategorias
  mscategorias:
    container_name: mscategorias
    image: figonzal/mscategorias:v1.0.0
    networks:
      - RED_TPS
    depends_on:
      - mysql

  #Definicion servicio msnoticias
  msnoticias:
    container_name: msnoticias
    image: figonzal/msnoticias:v1.0.0
    networks:
      - RED_TPS
    depends_on:
      - mysql
      - mscategorias

  #Definicion servicio Msnoticias-api
  ms-noticias-api:
    container_name: ms-noticias-api
    image: ecreyes/ms-noticias-api:v1.0.3
    networks:
      - RED_TPS
    depends_on:
      - mysql
      - msusuarios
      - msfavoritos
      - mscategorias
      - msnoticias

  #Definicion servicio apigateway
  apigateway:
    container_name: apigateway
    image: figonzal/apigateway:v1.0.0
    ports:
      - "80:8080"
    networks:
      - RED_TPS
    depends_on:
      - mysql
      - msusuarios
      - msfavoritos
      - mscategorias
      - msnoticias
      - ms-noticias-api

  #Servicio de espera para apigateway
  wait_for_apigateway:
    container_name: w4d5
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
      - mscategorias
      - msusuarios
      - msnoticias
      - msfavoritos
      - apigateway
      - ms-noticias-api
    networks:
      - RED_TPS
    command: apigateway:8080

  #Servicio de espera para servicios (Msfavoritos y Msnoticias-API)
  wait_for_favoritos_noticias_api:
    container_name: w4d4
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
      - mscategorias
      - msusuarios
      - msnoticias
      - msfavoritos
      - ms-noticias-api
    networks:
      - RED_TPS
    command: msfavoritos:8090 ms-noticias-api:3000

  #Servicio de espera para servicios (MsUsuario y MsNoticias)
  wait_for_usuarios_noticias:
    container_name: w4d3
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
      - mscategorias
      - msusuarios
      - msnoticias
    networks:
      - RED_TPS
    command: msnoticias:8090 msusuarios:8090

  #Servicio de espera para mscategoria (servicio base)
  wait_for_mscategorias:
    container_name: w4d2
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
      - mscategorias
    networks:
      - RED_TPS
    command: mscategorias:8090

  #Servicio de espera para mysql
  wait_for_mysql:
    container_name: w4d
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
    networks:
      - RED_TPS
    command: mysql:3306

networks: 
  RED_TPS:
    name: RED_TPS

volumes:
  db-data: